version: "3" ## especifica a versão do docker-compose file

services: ## Define um serviço
  # dbPostegres:
  #   image: postgres:latest
  #   container_name: "postgres-tepre"
  #   environment:
  #     - POSTGRES_DB=allTodo
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=123456
  #   volumes:
  #     - "./data/postgres:/var/lib/docker/postgresql/data"
  #   # networks:
  #   #   backend:
  #   #     ipv4_address: 172.21.0.3
  #   ports:
  #     - 5432:5432
  # #   deploy:
  # #     resources:
  # #       limits:
  # #         memory: 4096M
  # #         cpus: '1.5'
  # #       reservations:
  # #         memory: 2048M

  # redis:
  #   image: redis
  #   command: redis-server
  #   # --requirepass Redis2019!
  #   # networks:
  #   #   backend:
  #   #     ipv4_address: 172.21.0.2
  #   ports:
  #     - "6379:6379"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 4096M
  #         cpus: '1.5'
  #       reservations:
  #         memory: 2048M

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # kafdrop:
  #   image: obsidiandynamics/kafdrop:latest
  #   depends_on:
  #     - kafka
  #   ports:
  #     - 19000:9000
  #   environment:
  #     KAFKA_BROKERCONNECT: kafka:29092

  # mysqlsrv:
  #   image: mysql:latest
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "12345"
  #     MYSQL_DATABASE: "testedb"
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - "./data/mysql:/var/lib/docker/mysqlql/data"
  #   networks:
  #     backend:
  #       ipv4_address: 172.21.0.4

# networks:
#   backend:
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.21.0.0/16